# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/oleksiy/git/simshell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/oleksiy/git/simshell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oleksiy/git/simshell/CMakeFiles /Users/oleksiy/git/simshell//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oleksiy/git/simshell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimShell_GP

# Build rule for target.
SimShell_GP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_GP
.PHONY : SimShell_GP

# fast build rule for target.
SimShell_GP/fast:
	$(MAKE) $(MAKESILENT) -f gp/CMakeFiles/SimShell_GP.dir/build.make gp/CMakeFiles/SimShell_GP.dir/build
.PHONY : SimShell_GP/fast

#=============================================================================
# Target rules for targets named SimShell_GSMA

# Build rule for target.
SimShell_GSMA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_GSMA
.PHONY : SimShell_GSMA

# fast build rule for target.
SimShell_GSMA/fast:
	$(MAKE) $(MAKESILENT) -f gsma/CMakeFiles/SimShell_GSMA.dir/build.make gsma/CMakeFiles/SimShell_GSMA.dir/build
.PHONY : SimShell_GSMA/fast

#=============================================================================
# Target rules for targets named SimShell_LUAWRAP

# Build rule for target.
SimShell_LUAWRAP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_LUAWRAP
.PHONY : SimShell_LUAWRAP

# fast build rule for target.
SimShell_LUAWRAP/fast:
	$(MAKE) $(MAKESILENT) -f lua/CMakeFiles/SimShell_LUAWRAP.dir/build.make lua/CMakeFiles/SimShell_LUAWRAP.dir/build
.PHONY : SimShell_LUAWRAP/fast

#=============================================================================
# Target rules for targets named SimShell_CAP

# Build rule for target.
SimShell_CAP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_CAP
.PHONY : SimShell_CAP

# fast build rule for target.
SimShell_CAP/fast:
	$(MAKE) $(MAKESILENT) -f cap/CMakeFiles/SimShell_CAP.dir/build.make cap/CMakeFiles/SimShell_CAP.dir/build
.PHONY : SimShell_CAP/fast

#=============================================================================
# Target rules for targets named SimShell_LUALIB

# Build rule for target.
SimShell_LUALIB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_LUALIB
.PHONY : SimShell_LUALIB

# fast build rule for target.
SimShell_LUALIB/fast:
	$(MAKE) $(MAKESILENT) -f Lua5.3/CMakeFiles/SimShell_LUALIB.dir/build.make Lua5.3/CMakeFiles/SimShell_LUALIB.dir/build
.PHONY : SimShell_LUALIB/fast

#=============================================================================
# Target rules for targets named SimShell_MBED

# Build rule for target.
SimShell_MBED: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_MBED
.PHONY : SimShell_MBED

# fast build rule for target.
SimShell_MBED/fast:
	$(MAKE) $(MAKESILENT) -f mbed/CMakeFiles/SimShell_MBED.dir/build.make mbed/CMakeFiles/SimShell_MBED.dir/build
.PHONY : SimShell_MBED/fast

#=============================================================================
# Target rules for targets named SimShell_MBEDTLS

# Build rule for target.
SimShell_MBEDTLS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_MBEDTLS
.PHONY : SimShell_MBEDTLS

# fast build rule for target.
SimShell_MBEDTLS/fast:
	$(MAKE) $(MAKESILENT) -f mbedtls-3.5.1/library/CMakeFiles/SimShell_MBEDTLS.dir/build.make mbedtls-3.5.1/library/CMakeFiles/SimShell_MBEDTLS.dir/build
.PHONY : SimShell_MBEDTLS/fast

#=============================================================================
# Target rules for targets named SimShell_PCSC

# Build rule for target.
SimShell_PCSC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_PCSC
.PHONY : SimShell_PCSC

# fast build rule for target.
SimShell_PCSC/fast:
	$(MAKE) $(MAKESILENT) -f pcsc/CMakeFiles/SimShell_PCSC.dir/build.make pcsc/CMakeFiles/SimShell_PCSC.dir/build
.PHONY : SimShell_PCSC/fast

#=============================================================================
# Target rules for targets named SimShell_SHELL

# Build rule for target.
SimShell_SHELL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell_SHELL
.PHONY : SimShell_SHELL

# fast build rule for target.
SimShell_SHELL/fast:
	$(MAKE) $(MAKESILENT) -f shell/CMakeFiles/SimShell_SHELL.dir/build.make shell/CMakeFiles/SimShell_SHELL.dir/build
.PHONY : SimShell_SHELL/fast

#=============================================================================
# Target rules for targets named SimShell

# Build rule for target.
SimShell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimShell
.PHONY : SimShell

# fast build rule for target.
SimShell/fast:
	$(MAKE) $(MAKESILENT) -f shell/CMakeFiles/SimShell.dir/build.make shell/CMakeFiles/SimShell.dir/build
.PHONY : SimShell/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SimShell"
	@echo "... SimShell_CAP"
	@echo "... SimShell_GP"
	@echo "... SimShell_GSMA"
	@echo "... SimShell_LUALIB"
	@echo "... SimShell_LUAWRAP"
	@echo "... SimShell_MBED"
	@echo "... SimShell_MBEDTLS"
	@echo "... SimShell_PCSC"
	@echo "... SimShell_SHELL"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

